### ISSUE TITLE
[FR] Rotation flag

### ISSUE THREAD

**Issue by Hely0n** [roamingthings/spyglass#12]
It would be a great feature to rotate the image, as many camera mounts for printers are upside down (for Ender 3 at least).

**Comment by Hely0n** [comment]
I just implemented it myself. As I have never done a PR on Github, I will try my first tomorrow here :)

**Comment by Hely0n** [comment]
#13

**Comment by mryel00** [comment]
I will close this issue as you already made a PR for it.
