### ISSUE TITLE
Documentation for adding Spyglass as a service

### ISSUE THREAD

**Issue by Hely0n** [roamingthings/spyglass#15]
I added Spyglass as a systemctl service, so it autostarts and is controllable like crowsnest. This could maybe be added to the Readme:

Step 1:  Create and open a service description
`sudo nano /etc/systemd/system/spyglass.service`

Step 2: Insert the following text:

> [Unit]
> Description=Spyglass
> 
> [Service]
> Type=simple
> ExecStart=/usr/bin/python3 <your absolute path to spyglass>/run.py <your optional parameters>
> 
> [Install]
> WantedBy=multi-user.target

Step 3: Reload systemcontrol
`sudo systemctl daemon-reload`

Step 4: Enable Autostart of Spyglass
`sudo systemctl enable spyglass.service`

Step 4.5: Maybe you have to disable crowsnest first, to prevent port collision:
`sudo systemctl stop crowsnest.service && sudo systemctl disable crowsnest.service`

Step 5: Start your new Spyglass Service:
`sudo systemctl start spyglass.service`

Note that as far as I know, this only works on debian-based systems like Raspberry Pi OS and MainsailOS

**Comment by mryel00** [comment]
This is a nice idea but I am hesitant to add it to the readme. This is something you could get by googling in a few minutes.
I will write an How-To-Get-Started message as the last message for the [Raspberry Camera Module 3 support?](https://discord.com/channels/758059413700345988/1064270770114670673) thread on the support forum of the [Mainsail Discord](https://discord.gg/mainsail) before it will get locked as spyglass isn't supported officially by Crowsnest and Mainsail for now. I will add this there if you allow it.
@roamingthings what's your opinion, should we add it to the readme?

**Comment by roamingthings** [comment]
Could be interesting to have this in a separate part of the documentation. Not everything has to go to the main `README.md`

**Comment by Hely0n** [comment]
> This is a nice idea but I am hesitant to add it to the readme. This is something you could get by googling in a few minutes. I will write an How-To-Get-Started message as the last message for the [Raspberry Camera Module 3 support?](https://discord.com/channels/758059413700345988/1064270770114670673) thread on the support forum of the [Mainsail Discord](https://discord.gg/mainsail) before it will get locked as spyglass isn't supported officially by Crowsnest and Mainsail for now. I will add this there if you allow it. @roamingthings what's your opinion, should we add it to the readme?


Yeah in theory, it's just googling, but I found out there are many ways suggested like via crontab or rc.d (which doesn't even work anymore, at least for scripts to run at shutdown). That's why I thought this would be helpful, especially for users that are unfamiliar with linux.

**Comment by Hely0n** [comment]
As I'm not familiar with GitHub (this was even my first PR), I would leave it up to you 😄
