### ISSUE TITLE
Typo on autofocus description and default example

### ISSUE THREAD

**Issue by JustinQuintero** [roamingthings/spyglass#18]
in the description for autofocus it lists two options, there is a typo for the option "continuous", it is currently listed as "continous"
also in the "Starting the server without any argument" default example the same typo for continuous is shown. 

![Screenshot 2023-02-03 231143](https://user-images.githubusercontent.com/14301527/216748045-d6f027d7-4448-4a67-8f08-ea811a934004.png)

**Comment by roamingthings** [comment]
Thank you @JustinQuintero for pointing that our. I've created #20 to address this
