### ISSUE TITLE
FR: Add a release process to allow versioning of the application

### ISSUE THREAD

**Issue by roamingthings** [roamingthings/spyglass#19]
At the moment spyglass does not have a release process. Changes/pull requests are directly merged into the main branch.

For the future it would be nice to have a release process with versioning.

As a versioning scheme like [semver](https://semver.org) seems reasonable.

At the moment there are a lot of questions:
* How to manage last/current versions in branches?
* How is the process of creating a new release?
  * GitHub and/or PiPy?
  * Use GitHub Actions or a custom script?

**Comment by meteyou** [comment]
semver is needed if we want to update via moonraker update_manager. There are also different options.

**update commits:**
- update every commit (type: git_repo; channel: dev)
- update from git tag to git tag (type: git_repo; channel: beta)

**update releases:**
- update to release bundle files (type: zip; channel: stable)
- update to release bundle files and pre-release (type: zip; channel: beta)

git_repo is used by klipper/moonraker right now. You can also use it with a develop branch and merge a release to the master/main branch, and the update manager will only check the master/main branch.

**Comment by roamingthings** [comment]
@meteyou Can you point me to some place where I can read more about that? At the moment I have no idea how to set this up.

**Comment by mryel00** [comment]
Solved by #35 and #54
