### ISSUE TITLE
FR: Add Support for Moonraker Update Manager

### ISSUE THREAD

**Issue by roamingthings** [roamingthings/spyglass#45]
Add the ability to update an installation of Spyglass using the Moonraker update manager

**Comment by stijnb1234** [comment]
Would be great! Crowsnest uses the following file: https://github.com/mainsail-crew/crowsnest/blob/master/tools/install.sh

And then your configuration:
```ini
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
install_script: tools/install.sh
```
