### ISSUE TITLE
Reduce resource usage of spyglass

### ISSUE THREAD

**Issue by bodak** [roamingthings/spyglass#46]
I have been experiencing `MCU 'mcu' shutdown: Timer too close` errors lately suggesting that my RPi is overloaded.
I noticed that spyglass service is running 8 processes and consuming over 30% cpu.
<img width="422" alt="image" src="https://user-images.githubusercontent.com/6807878/226869154-f74785c3-3906-4ac4-8bc2-97f785ff717f.png">

Is there any option to reduce this?

I have unsuccessfully tried:
- updating to the latest spyglass
- looking through your code, but haven't seen where you specify the number of handlers for a server or a way to reduce threads.
- reduce the resolution of the camera

In a resource constrained situation, I would rather have the camera server fail / be reduced to snapshots than the print shutting down.

**Comment by roamingthings** [comment]
It's unusual to have so many processes. How many streams do you have active at the same time?

**Comment by mryel00** [comment]
We can't do anything about that. We are using the [picamera2](https://github.com/raspberrypi/picamera2) module and that is spawning that many processes if I'm not completely wrong. There is also another project that can use the module v3: [camera-streamer](https://github.com/ayufan/camera-streamer) from ayufan but it's need manual compiling and doesn't give much benefits over spyglass for the module v3. In my testings it's generating the same amount of cpu load. So it seems more like an issue corresponding to the hardware of the pi.
The best and simplest solution for now would be to reduce your fps this should lower the cpu usage.
I can understand that you want some kind of automatic throtteling for the stream but that would be a bit harder to implement as I'm not completely sure how to change the fps while the camera is running. The processes are constantly pulling new frames in the background from the camera and decode them. This is generating cpu usage in the background even if you don't have any stream open. At the moment there isn't anything we can do about that sadly except for lowering the fps in your settings.
The only solution I can think of now for the background cpu usage could be something like starting and stopping the camera whenever someone connects or disconnects resulting in a delay before you can see the stream in the webui or mobileraker.
