### ISSUE TITLE
Add support for usage with Fluidd

### ISSUE THREAD

**Issue by brian000** [roamingthings/spyglass#49]
Spyglass doesn't seem to work well with Fluidd, as it (Fluidd) adds extra parameters to the URI which Spyglass does not recognize.

`http://voron0.local/webcam/?action=snapshot&cacheBust=1683694863063` (or anything) returns a 404.  Browsing to it shows the stream/snapshot as expected, but Fluidd seems to always add that `cacheBust` parameter.

**Comment by mryel00** [comment]
Hello,
we are already aware of that problem and there is already an active PR #42. Currently spyglass is comparing urls exactly to the given url and that PR would make it possible to even use Adaptive Framerate.
Sadly the PR owner didn't respond the last 2 months, I didn't get time yet to work myself into that code and still need 2-3 weeks before I get enough time. The PR is already working, just got a few minor bugs left, needs a bit of refactoring and then it could be already published.
I will try my best to get it working asap.
