### ISSUE TITLE
Automatic updating broken?

### ISSUE THREAD

**Issue by stijnb1234** [roamingthings/spyglass#56]
I've installed Spyglass following these steps:
1. `git clone https://github.com/roamingthings/spyglass.git`
2. `make install`
3. Restarted the Raspberry Pi
4. Installed the updater part inside the moonraker config.'
5. Restarted Moonraker
6. See Spyglass in the update list as 'Invalid'
- Soft recovery gives: `Recovery attempt failed, repo state not pristine`
- Hard recovery gives: `Repo has not been verified, clone aborted`

How can I fix this?

EDIT:
I've tried running `make upgrade-moonraker`, but still the same issue.

**Comment by stijnb1234** [comment]
Had to update Moonraker to the latest version to fix the issue.

**Comment by mryel00** [comment]
@stijnb1234 Thank you for reporting and posting your solution. I will maybe look into that later.
Was this on a freshly installed MainsailOS, or what image did you use and when was your last update?
