### ISSUE TITLE
How do I uninstall spyglass?

### ISSUE THREAD

**Issue by iiiiiiiiddddddkkkkkkk** [roamingthings/spyglass#58]

**Comment by mryel00** [comment]
Some more information on how exactly you installed it, would be nice.
So there are currently two options to install it, with two different uninstall methods:

1. You install it as a package to use it inside your own python programs and to run it directly from console: `python -m pip install .` Then just run `pip uninstall spyglass`
2. You installed it as a service: `make install`. Then just run `cd ~/spyglass && make uninstall` like stated inside the [Install](https://github.com/roamingthings/spyglass/blob/main/README.md#install-and-run-as-a-service) section
