### ISSUE TITLE
White Balance is not working

### ISSUE THREAD

**Issue by nlincke** [roamingthings/spyglass#66]
Hey,

i am pretty sure that this is not a bug but a user error.
My pi cam is working fine but if the light situation changes a little the white balance fails.

Any recommendation how to fix this?

Any help is appreciated!

**Comment by mryel00** [comment]
Sry, I somehow forgot to reply you.

Overall this isn't something from Spyglass directly, but libcamera.
Normally you can change the auto white balance (`awb`) mode, but currently we don't have the control options merged onto the main branch yet.
It's currently on a draft branch. I will finish the branch soon, when I get more time again.
